Revert "fix:Module build failed: Error: Failed to load plugin import: Cannot find module eslint-plugin-import in heroku v2"
This reverts commit 54ded088cdb7d3503cea664a39a3c3ba5ee1849c.